on:
  push:
    branches: master
  schedule:
    - cron: "0 16 * * *"
name: Broken links?
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r *
      - name: Fail?
        run: exit ${{ steps.lc.outputs.exit_code }}